# Generated by Django 3.1.1 on 2020-10-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePdf', models.FileField(upload_to='')),
                ('content', models.TextField()),
                ('task_id', models.CharField(max_length=50)),
            ],
        ),
    ]
